apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshop
  namespace: ops
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop
  namespace: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshop
subjects:
- kind: ServiceAccount
  name: workshop
  namespace: ops
