apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
  name: k8s-workshop
  namespace: apps
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot
  type: ClusterIP
